### ISSUE TITLE
Why import as code.cloudfoundry.org/bytefmt?

### ISSUE THREAD

**Issue by shawnps** [cloudfoundry/bytefmt#11]
Hi, just out of curiosity, why should this be imported as `code.cloudfoundry.org/bytefmt`? Is there a plan to move it off of GitHub at some point? Thanks!

**Comment by ematpl** [comment]
Hi, @shawnps,

Cloud Foundry projects currently use three different GitHub organizations, [cloudfoundry](https://github.com/cloudfoundry), [cloudfoundry-incubator](https://github.com/cloudfoundry-incubator), and [cloudfoundry-attic](https://github.com/cloudfoundry-attic), to host their Git repositories, which align with the lifecycle status of projects (incubating, active, and obsolete). We introduced the "code.cloudfoundry.org" import path domain as a way to enable those repositories to move through those lifecycle stages without affecting their consumers. More detailed information is present in the [import-path proposal circulated to the CF community](https://docs.google.com/document/d/1iaucrX9V5NEDDrZYW8ooU68PFHQGMphMn_Dlsoya7WQ/edit) and in the [`go-fetcher` redirection service](https://github.com/cloudfoundry/go-fetcher). As you've noted, of course, this decoupling would allow the entire collection of repositories to migrate transparently to a different Git provider, but I'm not aware of any plans to do so.

Thanks,
Eric, CF Runtime Diego PM

**Comment by shawnps** [comment]
Thanks for the info!
