### ISSUE TITLE
ToBytes should handle floats

### ISSUE THREAD

**Issue by DanielOaks** [cloudfoundry/bytefmt#13]
Yo, thanks for the library! No biggie, but it's a bit strange that `ToBytes` doesn't seem to handle floats (only ints). For instance, running `ToBytes("20MB")` gives you the size as expected, but `ToBytes("1.5MB")` gives you _"Byte quantity must be a positive integer with a unit of measurement like M, MB, G, or GB"_.

All else fails I might throw in a PR for this myself at some point. Thanks again for making this library :)

**Comment by ematpl** [comment]
Thanks, @DanielOaks, I had noticed that asymmetry a while back as well. I don't think any CF project has needed the decimal-precision conversion back into bytes, so it likely never got implemented. If you'd like to submit a PR for it, that would be welcome!

Best,
Eric, CF Diego PM

**Comment by DanielOaks** [comment]
Fixed with #14, thanks for merging!
