### ISSUE TITLE
code in directory /home/travis/gopath/src/github.com/cloudfoundry/bytefmt expects import "code.cloudfoundry.org/bytefmt"

### ISSUE THREAD

**Issue by chmduquesne** [cloudfoundry/bytefmt#15]
My build is broken because code.cloudfoundry.org cannot be pinged. It would be nice to either repair this domain, or to fix the code to depend only on github.

I hope it's not an outage :-/

**Comment by DanielOaks** [comment]
Just making sure, did you run `go get code.cloudfoundry.org/bytefmt` to get bytefmt? From the looks of it I'm able to grab it from there.

If you grab it using `go get github.com/cloudfoundry/bytefmt` instead you'll get the above issue since that's not the intended clone path.

**Comment by chmduquesne** [comment]
Ah ok. I used to be able to grab it from GitHub. I will check tomorrow if I
can do what you say.

**Comment by emalm** [comment]
Hi, @chmduquesne,

We started enforcing a canonical import path of `code.cloudfoundry.org/bytefmt` in this repository about 10 months ago, so if you're still retrieving this package via `go get github.com/cloudfoundry/bytefmt` or importing it from that directory in your GOPATH it will fail with that error. Are you able to resolve this error after updating this import path?

Please also note that you can still run `git clone github.com/cloudfoundry/bytefmt` to retrieve the repository from GitHub. In fact, that's what `go get` does underneath, and how the Cloud Foundry community has this repository [submoduled into larger projects](https://github.com/cloudfoundry/diego-release/blob/v1.30.0/.gitmodules#L241-L244) but still located at the `code.cloudfoundry.org/bytefmt` path in the GOPATH source tree.

Thanks,
Eric, CF Diego PM

**Comment by chmduquesne** [comment]
Hello,

Yes, importing as code.cloudfoundry.org/bytefmt fixed the problem. Thank you!
