### ISSUE TITLE
support for 0 byte objects in ToBytes

### ISSUE THREAD

**Issue by tdineshramkumar** [cloudfoundry/bytefmt#20]

**Comment by sunjayBhatia** [comment]
@tdineshramkumar Can you provide:
- The inputs you are providing to the `ToBytes` function
- The current outputs
- The expected outputs

**Comment by tdineshramkumar** [comment]
ToBytes returns an error for zero size objects like "0", "0K", "0M".  As these are valid sizes, returning 0 without error is expected.

**Comment by rjeczalik** [comment]
> As these are valid sizes, returning 0 without error is expected.

@tdineshramkumar This is not true, ToBytes errors on 0 -> https://play.golang.org/p/XXOrmfynjr8. At very minimum ByteSize should be consistent and return "0B" string for 0.

**Comment by rjeczalik** [comment]
> As these are valid sizes, returning 0 without error is expected.

@tdineshramkumar ToBytes errors on 0 -> https://play.golang.org/p/XXOrmfynjr8

At very minimum ByteSize should be consistent and return "0B" string for 0.

**Comment by dsoprea** [comment]
This is an issue for me, too:
1. In non-zero cases, people know what the unit is. In zero-size cases, they don't.
2. In non-zero cases, printing will align one way. In zero-size cases, they'll align the other way:

```
    NAME    | UNCOMP SIZE | COMP SIZE | MODE |         MIME TYPE         |          MODIFIED AT          | ENCODING |   CRC    | METADATA?  
+-----------+-------------+-----------+------+---------------------------+-------------------------------+----------+----------+-----------+
  .aa       |           0 |         0 | 0644 | application/octet-stream  | Sun, 28 Jul 2019 04:10:36 EDT | bzip2    | 811c9dc5 | false      
  bb        |           0 |         0 | 0644 | application/octet-stream  | Sun, 28 Jul 2019 04:10:40 EDT | bzip2    | 811c9dc5 | false      
  child/.dd | 29B         | 78B       | 0644 | text/plain; charset=utf-8 | Sun, 28 Jul 2019 04:10:58 EDT | bzip2    | b7b3c503 | false      
  child/cc  | 29B         | 82B       | 0644 | text/plain; charset=utf-8 | Sun, 28 Jul 2019 04:10:56 EDT | bzip2    | 30eb8ad8 | false      
```

So, yeah. Thanks for that. We're forced to hack something together because this one corner case is intentionally overlooked.

**Comment by dsoprea** [comment]
It's not clear if this was fixed or just aged out.

**Comment by sunjayBhatia** [comment]
The feed above links to a PR that is open for this issue that should supersede it. I see you opened a similar issue for providing a unit for size 0, we would be open to a PR for that as well @dsoprea
