### ISSUE TITLE
code.cloudfoundry.org/bytefmt in not found

### ISSUE THREAD

**Issue by tbarbugli** [cloudfoundry/bytefmt#21]
```
404 Not Found: Requested route ('code.cloudfoundry.org') does not exist.
```

**Comment by DanielOaks** [comment]
Hmm I'm not able to repro this. @tbarbugli if you run this command, it should download bytefmt and put it into the right place:
```
go get -u code.cloudfoundry.org/bytefmt
```

**Comment by sunjayBhatia** [comment]
I believe there was an outage on the app that does the `code.cloudfoundry.org` redirects yesterday which is probably why you saw that

**Comment by tbarbugli** [comment]
any reason this package is using cloudfoundry instead of Github?

**Comment by sunjayBhatia** [comment]
I believe its a cloudfoundry convention and also to potentially prevent us from having issues if the package needs to be moved away from github

(there could be other/better reasons, but thats all I can think of at the moment)

**Comment by sunjayBhatia** [comment]
closing this for now since it was an issue with the redirect app, everything should be fixed

**Comment by emalm** [comment]
@tbarbugli @sunjayBhatia Historical context on the `code.cloudfoundry.org` import path: https://docs.google.com/document/d/1iaucrX9V5NEDDrZYW8ooU68PFHQGMphMn_Dlsoya7WQ/edit

In addition to decoupling the import path from the hosting service (GitHub), it smoothes over import-path breakage when teams' repos move between Cloud Foundry Foundation GitHub orgs as part of the governance conventions.
