### ISSUE TITLE
Support for Petabyte and Exabyte

### ISSUE THREAD

**Issue by a4abhishek** [cloudfoundry/bytefmt#22]
Since the datatype of bytes is always `uint64`, this can handle utpo **18446744073709551615** Bytes. Converting this number in "human-readable byte string" format it gives **16777216T**. This can be further Reduced up to `Exabytes`.

**Comment by heyjcollins** [comment]
You created [a PR for this](https://github.com/cloudfoundry/bytefmt/pull/23) so I'm going to close this issue and we can manage the conversation going forward via [the PR](https://github.com/cloudfoundry/bytefmt/pull/23).
