### ISSUE TITLE
Whitespace between value and unit breaks ToBytes

### ISSUE THREAD

**Issue by dank** [cloudfoundry/bytefmt#28]
```
10 TB
50 MB
12 KB
```

Inputs like above causes `ToBytes` to error out because the whitespace is included when it tries to `ParseFloat` right after.

**Comment by dank** [comment]
I created a potential PR for this issue. However,  I do not have a Cloudfoundry "CLA". With all due respect, I am not going to fill out a form to contribute to open source projects. Feel free to take the PR and re-open it if you have a "CLA".

**Comment by heyjcollins** [comment]
Thanks @dank,

We'll review and proceed from there.
Given the PR, I'm going to close this out.

Feel free to reopen if you've got further comments for the issue that wouldn't be appropriate for the PR itself.

Cheers,

Josh

**Comment by dank** [comment]
Can we reopen this issue because my PR (#29) got closed for not having a CLA?
