### ISSUE TITLE
Clarification of NOTICE

### ISSUE THREAD

**Issue by utkarsh2102** [cloudfoundry/bytefmt#30]
Line 3 in NOTICE states,
https://github.com/cloudfoundry/bytefmt/blob/854d396b647c90b5a45646f9dcc2c9cd08ea8d51/NOTICE#L3

Could you perhaps be more explicit about which software and what files and how it is being used, etc? :)

**Comment by heyjcollins** [comment]
Hi @utkarsh2102 - it refers to all the files included in this repository. I'm afraid I can't provide more details as those who originally submitted the changes have rolled off the team. I'm going to close this out.
